version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Entering project root…"
      - cd podcaster

      - echo "Installing backend dependencies…"
      - cd backend
      - npm install
      - cd ..

      - echo "Installing frontend dependencies…"
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "No build step needed for this backend-only project."

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - chmod +x scripts/*.sh
      - cp appspec.yml .
      - cp -r scripts .

artifacts:
  files:
    - '**/*'
  base-directory: podcaster
