AWSTemplateFormatVersion: '2010-09-09'
Description: Sets up EC2 Instance, Security Group, and IAM Role for Podcaster App deployment.

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  AmiId:
    Description: AMI ID for Amazon Linux 2 (find latest for your region)
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SshLocation:
    Description: The IP address range that can SSH into EC2
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range.

  AppPort:
    Description: Port the Node.js application will listen on
    Type: Number
    Default: 1000

  VpcId:
    Description: VPC ID to deploy resources into
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: Subnet ID to launch the EC2 instance into
    Type: AWS::EC2::Subnet::Id

Resources:
  PodcasterEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: SSMParameterStoreReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ssm:GetParameters
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mern-podcast-app/*'

  PodcasterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref PodcasterEC2Role

  PodcasterSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and App Port for Podcaster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref AppPort
          ToPort: !Ref AppPort
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PodcasterSG

  PodcasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      ImageId: !Ref AmiId
      IamInstanceProfile: !Ref PodcasterInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          GroupSet:
            - !Ref PodcasterSG
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: PodcasterServer-CFN
        - Key: Deploy
          Value: mern-podcast-app
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install ruby wget -y
          cd /home/ec2-user
          wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          sudo -u ec2-user -i <<'EOF'
          unset NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="/home/ec2-user/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16
          nvm alias default 16
          npm install pm2 -g
          EOF
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16
          nvm alias default 16
          npm install pm2 -g
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          rm -rf aws awscliv2.zip
          service codedeploy-agent start
          chkconfig codedeploy-agent on

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref PodcasterInstance

  PublicIp:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt PodcasterInstance.PublicIp

  PublicDnsName:
    Description: Public DNS name of the newly created EC2 instance
    Value: !GetAtt PodcasterInstance.PublicDnsName
